[package]
name = "houtamelo_utils_gdext"
version = "0.7.0"
authors = ["Houtamelo"]
edition = "2024"
description = "A collection of utilities shared between Houtamelo's GDExtension projects."
license = "MIT"
repository = "https://github.com/Houtamelo/houtamelo_utils_gdext"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
godot = { git = "https://github.com/Houtamelo/dead_gds_have_rights", features = ["experimental-threads"] }
rand = { version = "0.10", features = ["std"] }
rand_xoshiro = { version = "0.8" }
anyhow = "1.0"